fs: fix register pattern entry
westerndigitalcorporation/zenfs pull request #125
Opened 2022-01-02 05:32 UTC by SheldonZhong

RocksDB upstream no longer supports Regex. See the PR [here](https://github.com/facebook/rocksdb/pull/9264).

2022-01-02 06:54 UTC, MaisenbacherD approved these changes
Looks good to me

2022-01-03 10:46 UTC, metaspace commented
I get the following error when building:

```text
plugin/zenfs/fs/fs_zenfs.cc:1281:24: error: 'PatternEntry' is not a member of 'rocksdb::ObjectLibrary'
 1281 |         ObjectLibrary::PatternEntry("zenfs", false)
      |                        ^~~~~~~~~~~~
```

2022-01-03 12:08 UTC, skyzh commented
Should we also bump RocksDB version [here](https://github.com/westerndigitalcorporation/zenfs/blob/master/.github/workflows/smoke-test.yaml#L23)?

2022-01-03 12:39 UTC, metaspace commented
> Should we also bump RocksDB version [here](https://github.com/westerndigitalcorporation/zenfs/blob/master/.github/workflows/smoke-test.yaml#L23)?

Yes, that is the right place to bump RocksDB version. Right now we are held back by a bug in `db_stress`: https://github.com/westerndigitalcorporation/zenfs/issues/72. We need to fix that before bumping RocksDB version.

2022-01-04 07:42 UTC, aravind-wdc commented
Looks good!

2022-01-04 08:58 UTC, yhr requested changes
This will break percona server and terarkdb integration as they are currently both locked to older versions of rocksdb. We need to figure out how to deal with the public API break.

2022-01-04 15:33 UTC, SheldonZhong commented
It seems fine for percona-server as long as rocksdb and zenfs are both locked to the compatible versions in their repo. They could just bump up rocksdb along with zenfs. 

As for terarkdb, the patch facebook/rocksdb#9264 might be able to applied on it without much effort. But we might need to customize an API for it if terarkdb starts to diverge from rocksdb in the future.

2022-01-13 09:48 UTC, yhr commented
The upstream API breakage has now been mended and zenfs registration works again. See https://github.com/facebook/rocksdb/commit/1973fcba111fc451df69eb2ec38eb66c285f316f

2022-01-14 02:48 UTC, closed without merging