Quality of service patches
westerndigitalcorporation/zenfs pull request #161
Opened 2022-02-23 14:17 UTC by MaisenbacherD

Linking the RocksDB repo in the `README.md`.
Also fixing the output for `zenfs --version`.

Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>

2022-02-24 08:56 UTC, yhr requested changes
One small thing, otherwise this looks god

2022-02-24 08:56 UTC, yhr commented on README.md
> +ZenFS is a file system plugin that utilizes [RockDB](https://github.com/facebook/rocksdb)'s FileSystem interface to
Typo.. RockDB --> RocksDB

2022-02-24 11:41 UTC, MaisenbacherD commented on README.md
> +ZenFS is a file system plugin that utilizes [RockDB](https://github.com/facebook/rocksdb)'s FileSystem interface to
Fixed the typo :)

2022-02-24 12:24 UTC, yhr approved these changes

2022-02-24 12:26 UTC, yhr commented
pushed manually

2022-02-24 12:26 UTC, closed without merging

2022-02-24 17:48 UTC, MaisenbacherD commented
The second commit (4af9bb5c1e4d7443fb7feafa2adfd67088bbee27) was not merged :)

2022-03-01 08:12 UTC, yhr commented
fixed!