Fix gcc-11 and clang-12 compilation issues
westerndigitalcorporation/zenfs pull request #17
Opened 2021-06-09 12:53 UTC by inikep

Fix the following gcc-11 compilation issues:
```
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc: In member function ‘virtual rocksdb::IOStatus rocksdb::ZenFS::GetChildren(const string&, const rocksdb::IOOptions&, std::vector<std::__cxx11::basic_string<char> >*, rocksdb::IODebugContext*)’:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:532:19: error: loop variable ‘f’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Werror=range-loop-construct]
  532 |   for (const auto f : auxfiles) {
      |                   ^
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc: In member function ‘rocksdb::Status rocksdb::ZenFS::Mount(bool)’:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:862:19: error: loop variable ‘sm’ creates a copy from type ‘const std::pair<unsigned int, unsigned int>’ [-Werror=range-loop-construct]
  862 |   for (const auto sm : seq_map) {
      |                   ^~
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:903:19: error: loop variable ‘sm’ creates a copy from type ‘const std::pair<unsigned int, unsigned int>’ [-Werror=range-loop-construct]
  903 |   for (const auto sm : seq_map) {
      |                   ^~
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/util/zenfs.cc: In function ‘void rocksdb::list_children(rocksdb::ZenFS*, std::string)’:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/util/zenfs.cc:121:19: error: loop variable ‘f’ creates a copy from type ‘const std::__cxx11::basic_string<char>’ [-Werror=range-loop-construct]
  121 |   for (const auto f : result) {
      |                   ^
```

Fix the following clang-12 compilation issues:
```
In file included from /data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/zbd_zenfs.cc:27:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/io_zenfs.h:179:12: error: 'Skip' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  IOStatus Skip(uint64_t n);
           ^
In file included from /data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/util/zenfs.cc:16:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.h:327:20: error: 'LinkFile' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  virtual IOStatus LinkFile(const std::string& /*src*/,
                   ^
In file included from /data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:9:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.h:334:20: error: 'NumFileLinks' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  virtual IOStatus NumFileLinks(const std::string& /*fname*/,
                   ^
In file included from /data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:9:
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.h:341:20: error: 'AreFilesSame' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  virtual IOStatus AreFilesSame(const std::string& /*first*/,
                   ^
/data/mysql-server/wdc-8.0/storage/rocksdb/rocksdb/plugin/zenfs/fs/fs_zenfs.cc:974:23: error: local variable 's' will be copied despite being returned by name [-Werror,-Wreturn-std-move]
  if (!s.ok()) return s;
                      ^
```

2021-06-11 03:49 UTC, yhr requested changes
Thanks, the code changes looks good to me, but could you sign off your patches? 
git commit --signoff

2021-06-11 12:44 UTC, inikep commented
Sure, it's done.

2021-06-13 03:34 UTC, yhr approved these changes

2021-06-13 03:34 UTC, yhr commented
Looks good to me, thanks!

2021-06-13 03:34 UTC, merged