Bug fixes
westerndigitalcorporation/zenfs pull request #20
Opened 2021-06-21 20:30 UTC by aravind-wdc

2021-06-24 03:21 UTC, yhr requested changes
The commit message should document WHY the change is made. Please explain in the commit message why you're changing the type. Cheers!

2021-06-24 13:47 UTC, aravind-wdc commented
> The commit message should document WHY the change is made. Please explain in the commit message why you're changing the type. Cheers!

Updated the commit message.

2021-06-26 17:57 UTC, yhr approved these changes

2021-06-26 17:57 UTC, yhr commented
Thanks!

2021-06-26 17:57 UTC, merged