Prevent concurrent write opens/migrations
westerndigitalcorporation/zenfs pull request #200
Opened 2022-06-03 11:27 UTC by yhr

Adresses #195

2022-06-03 12:34 UTC, metaspace commented
```
In file included from plugin/zenfs/fs/io_zenfs.cc:11:
plugin/zenfs/fs/io_zenfs.cc: In constructor 'rocksdb::ZonedWritableFile::ZonedWritableFile(rocksdb::ZonedBlockDevice*, bool, std::shared_ptr<rocksdb::ZoneFile>)':
plugin/zenfs/fs/io_zenfs.cc:769:20: error: 'using element_type = class rocksdb::ZoneFile' {aka 'class rocksdb::ZoneFile'} has no member named 'IsOpenForWrite'; did you mean 'IsOpenForWR'?
  769 |   assert(zoneFile->IsOpenForWrite());
      |                    ^~~~~~~~~~~~~~
```

2022-06-08 09:13 UTC, metaspace requested changes

2022-06-14 11:31 UTC, yhr commented
> `AquireWRLock()` -> `AcquireWRLock()`, same for `Try..`

doh! fixed!

2022-06-15 07:20 UTC, yhr commented on fs/fs_zenfs.cc
> -    if (zoneFile->IsOpenForWR())
I'll update the commit message. The behavior should be ok  as it is consistent with posix file systems.

2022-06-15 08:08 UTC, metaspace approved these changes

2022-06-15 09:29 UTC, merged