db_stress verification
westerndigitalcorporation/zenfs pull request #209
Opened 2022-06-17 14:17 UTC by MaisenbacherD

This PR fixes a verification error that occurred when executing db_stress:

```
./db_stress --ops_per_thread=1000 --reopen=5 --db=dbname --fs-uri=zenfs://dev:nvmeXnX --read_fault_one_in=0
```

When boost::filesystem is enabled instead of filesystem_utility.h the "fs: Do not prepend path with '/' in `FormatPathLexically`" commit is necessary otherwise executing db_stress will end in the following error:
`open error: IO error: RenameLink: Failed to find the linked file`

If filesystem_utility.h is enabled the "fs: Do not prepend path with '/' in `FormatPathLexically`" commit is not strictly necessary.

2022-06-17 14:26 UTC, MaisenbacherD commented
Attention: "fs: Do not prepend path with '/' in FormatPathLexically" requires a ZenFS major version bump.

2022-06-20 12:57 UTC, MaisenbacherD commented
Version bump is not needed anymore, as the commit "fs: Do not prepend path with '/' in FormatPathLexically" was removed because boost is not being used as a filesystem path replacement.

2022-08-17 08:42 UTC, yhr commented
Let's get this reviewed & merged

2022-08-22 08:34 UTC, yhr approved these changes

2022-08-24 12:08 UTC, metaspace requested changes
LGTM, but would prefer splitting in two commits, 1 for refactor, 1 for bug fix.

2022-08-24 12:33 UTC, metaspace approved these changes

2022-08-24 14:03 UTC, merged