Fix Segmentation fault while enable zenfs gc.
westerndigitalcorporation/zenfs pull request #250
Opened 2022-12-01 09:48 UTC by ywang-wnlo

When zone become full, the `wp_` will be negative value, so change to use `max_capacity_`.

2022-12-06 12:07 UTC, yhr commented on fs/zbd_zenfs.cc
> +    if (z->IsFull()) {
Please change the code to do the garbage calculation only once (using IsFull() as a condition for how to do it)

2022-12-06 12:09 UTC, yhr requested changes
See my comment on the code. Apart from that you need to sign off your patch and push a new revision (git commit --amend --signoff && git push HEAD:<your pull req branch) for us to accept it. Thanks!

2022-12-06 12:19 UTC, ywang-wnlo commented
I changed the code, and force-pushed it. Is it OK?

2022-12-26 07:24 UTC, yhr commented
> I changed the code, and force-pushed it. Is it OK?

Yes, thanks! Our CI seems to be misbehaving though. I'll run the lint check and merge this manually when i'm back from vacation. Happy holidays @ywang-wnlo

2023-01-25 07:44 UTC, yhr commented
Merged via PR #256 . Thanks @ywang-wnlo !

2023-01-25 07:44 UTC, closed without merging