utils: format path for listing files
westerndigitalcorporation/zenfs pull request #33
Opened 2021-08-16 18:14 UTC by aravind-wdc

format the path provided by user, to list files.

Signed-off-by: Aravind Ramesh <aravind.ramesh@wdc.com>

2021-08-16 18:15 UTC, aravind-wdc commented
Fixes issue reported by https://github.com/westerndigitalcorporation/zenfs/issues/30

2021-08-16 19:33 UTC, yhr requested changes
The commit message does not provide a description of 1) what the issue is and 2) how this patch fixes it.

Also describe any other changes you have done (like returning an error if the directory does not exist)

2021-08-17 02:21 UTC, skyzh commented on util/zenfs.cc
> +  if (path.front() == '/')
`path.front()` and `path.back()` would return a dangling reference if the string is empty at this point. Shall we add something like
```
if (path.empty()) {
  path = "/";
}
```

here?

2021-08-17 02:25 UTC, skyzh commented on util/zenfs.cc
> +  if (path.front() == '/')
It turns out the C++ standard guarantees there would be a `\0` if string is empty. No issue here.

2021-08-17 07:39 UTC, aravind-wdc commented
$ sudo ./zenfs list --zbd=nvme0n1 --path=rocksdbtest/dbbench
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
   316552720    Aug 16 2021 23:07:43            000012.sst                      
   217338191    Aug 16 2021 23:07:43            000013.log                      
   194483993    Aug 16 2021 23:07:43            000014.sst                      
          16    Aug 16 2021 23:07:43            CURRENT                         
          37    Aug 16 2021 23:07:43            IDENTITY                        
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
         584    Aug 16 2021 23:07:43            MANIFEST-000004                 
        6317    Aug 16 2021 23:07:43            OPTIONS-000007 

$ sudo ./zenfs list --zbd=nvme0n1 --path=rocksdbtest/dbbench/
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
   316552720    Aug 16 2021 23:07:43            000012.sst                      
   217338191    Aug 16 2021 23:07:43            000013.log                      
   194483993    Aug 16 2021 23:07:43            000014.sst                      
          16    Aug 16 2021 23:07:43            CURRENT                         
          37    Aug 16 2021 23:07:43            IDENTITY                        
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
         584    Aug 16 2021 23:07:43            MANIFEST-000004                 
        6317    Aug 16 2021 23:07:43            OPTIONS-000007    
    
$ sudo ./zenfs list --zbd=nvme0n1 --path=rocksdbtest/dbbench/////
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
   316552720    Aug 16 2021 23:07:43            000012.sst                      
   217338191    Aug 16 2021 23:07:43            000013.log                      
   194483993    Aug 16 2021 23:07:43            000014.sst                      
          16    Aug 16 2021 23:07:43            CURRENT                         
          37    Aug 16 2021 23:07:43            IDENTITY                        
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
         584    Aug 16 2021 23:07:43            MANIFEST-000004                 
        6317    Aug 16 2021 23:07:43            OPTIONS-000007

$ sudo ./zenfs list --zbd=nvme0n1 --path=///rocksdbtest/dbbench/////
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
   316552720    Aug 16 2021 23:07:43            000012.sst                      
   217338191    Aug 16 2021 23:07:43            000013.log                      
   194483993    Aug 16 2021 23:07:43            000014.sst                      
          16    Aug 16 2021 23:07:43            CURRENT                         
          37    Aug 16 2021 23:07:43            IDENTITY                        
           0    Aug 16 2021 23:07:43            LOCK                            
       39116    Aug 16 2021 23:07:43            LOG                             
         584    Aug 16 2021 23:07:43            MANIFEST-000004                 
        6317    Aug 16 2021 23:07:43            OPTIONS-000007      

$ sudo ./zenfs list --zbd=nvme0n1 --path=///rocksdbtest/dbb/
Error: NotFound:  rocksdbtest/dbb/
$

2021-08-17 18:37 UTC, yhr approved these changes
Great, now i understand what was changed, thanks!

2021-08-18 05:05 UTC, merged