util: fixed memory leaks in zenfs utility
westerndigitalcorporation/zenfs pull request #53
Opened 2021-09-10 14:27 UTC by percona-ysorokin

Fixed leak in 'ZenFS::MkFS()' caused by a 'Superblock' allocated on
heap and never deallocated.

Fixed resource leak in 'ListZenFileSystems()' where 'opendir()' did not
have corresponding 'closedir()'

Reworked 'zbd_open()' and 'zenfs_mount()' functions so that they now
accept/return 'std::unique_ptr's for 'ZonedBlockDevice' and 'ZenFS'
instead of raw pointers. This fixed a number of memory leaks in
'zenfs' utility command handlers.

Fixed 'std::string's passed by value instead of by const reference in
some function signatures.

'--help' command text now shows that 'zenfs' utility supports 'dump'
command as well.

Fixed some minor formatting issues (still not fully clang-formatted).

Signed-off-by: Yura Sorokin <yura.sorokin@percona.com>

2021-09-15 06:58 UTC, yhr requested changes
Thanks for the PR, looks good over all - but there are some nitpicks (mostly coding style) that needs to be addressed.

It would have been easier to review if the different fixes had been split up in individual patches, please try to do that next time. Small, one logical change per commit, patches helps when bisecting for regressions as well.

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +using ZonedBlockDevicePtr = std::unique_ptr<ZonedBlockDevice>;
Please don't introduce new types unless it is really needed, we want to stick with rocksdb coding style (and I think adding types just makes the code harder to read - just another level of indirection)

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  auto zbd = zbd_open(false, true);
The only place I want auto to be used is for iterators in for loops - I'm very much in favor of typed languages :)

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  auto *zbdRaw = zbd.get();
See prev comment

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  auto s = zenfs_mount(zbd, &zenFS, true);
Same here, no need to use auto

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  auto s = zenfs_mount(zbd, &zenFS, true);
Please use full type declaration

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  for (const auto &p: zenFileSystems)
here auto makes sense

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  buffer.resize(buffer_sz);
It's nice to reduce the number of lines, but an allocation failure can still happen, right?

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  auto zbd = zbd_open(true, true);
No auto declarations please

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
> +  auto zbd = zbd_open(false, true);
No autos

2021-09-15 06:58 UTC, yhr commented on util/zenfs.cc
>    if (!s.ok()) {
Same here, please write out the type in stead

2021-09-15 07:42 UTC, yhr commented
zenfs integration testing ((util, smoke, quick performance test sets) passed

2021-09-15 13:08 UTC, percona-ysorokin commented
@yhr I addressed your comments:
- removed `ZonedBlockDevicePtr` and `ZenFSPtr` typedefs.
- `auto`s changed to explicit types
- removed formatting fixes
- reimplemented OOM check after buffer allocation in `zenfs_tool_copy_file()`
- removed utility help line fix (will be submitted as a separate PR)

2021-09-16 08:09 UTC, yhr approved these changes

2021-09-16 08:10 UTC, yhr commented
Looks good to me and passed integration testing

2021-09-16 08:11 UTC, merged