Zenfs docs
westerndigitalcorporation/zenfs pull request #58
Opened 2021-09-21 08:43 UTC by aravind-wdc

Addressed previous comments regarding the licensing information.

2021-09-21 09:15 UTC, yhr requested changes
Typo in the copyright statement, better fix that :)

2021-09-21 09:15 UTC, yhr commented on util/zenfs.8
> +(c) 2020-2021 Western Digital Corportation and its affiliates
Corportation -> Corporation

2021-09-21 10:26 UTC, aravind-wdc commented on util/zenfs.8
> +(c) 2020-2021 Western Digital Corportation and its affiliates
Oops. Fixed it.

2021-09-22 13:27 UTC, yhr approved these changes

2021-09-22 13:27 UTC, merged