Zenfs updates
westerndigitalcorporation/zenfs pull request #7
Opened 2021-04-23 05:14 UTC by aravind-wdc

`$ sudo ./zenfs list --zbd=nvme0n1 --path=rocksdbtest/dbbench
      138529    LOG
           0    LOCK
    67457871    000043.sst
     5585151    000054.sst
    20525927    000055.sst
     5616455    000057.sst
          16    CURRENT
          37    IDENTITY
        3045    MANIFEST-000004
        6141    OPTIONS-000007
`

`$ sudo ./zenfs mkfs --zbd=nvme0n1 --aux-path=/tmp/zenfs-aux --force
INFO: For ZBD /dev/nvme0n1, setting scheduler to mq-deadline.
ZenFS file system created. Free space: 3970899 MB
`

2021-04-23 07:18 UTC, yhr commented on fs/zbd_zenfs.h
> +  bool Set_Scheduler();
No mixing of _ and CamelCase, please remove the underscore

2021-04-23 08:16 UTC, yhr commented on fs/fs_zenfs.cc
> +  if (!readonly && !zbd_->Set_Scheduler()) {
It's better to have this in ZonedBlockDevice::Open, so please move it there

2021-04-23 08:16 UTC, yhr commented on fs/zbd_zenfs.cc
> +         fprintf(stderr, "Failed to set scheduler, error: %s\n", ErrorToString(errno).c_str());
Why not just open the file and write to it?

2021-04-23 08:19 UTC, yhr requested changes

2021-04-23 08:19 UTC, yhr commented on fs/zbd_zenfs.h
> +  bool Set_Scheduler();
Remove the underscore

2021-04-23 08:19 UTC, yhr commented on util/zenfs.cc
> +    fprintf(stdout, "%12lu\t%-32s\n", size, f.c_str());
There is no need to cap the fields to a certain size, right?

2021-04-23 08:19 UTC, yhr commented on fs/zbd_zenfs.cc
> +         fprintf(stderr, "Failed to set scheduler, error: %s\n", ErrorToString(errno).c_str());
Why not just open the file and write to it?

2021-04-27 08:43 UTC, aravind-wdc commented
Addressed all the comments.

2021-04-28 08:16 UTC, yhr approved these changes

2021-04-28 08:17 UTC, merged