fix: Handle faulty Acquire and Release calles on zones.
westerndigitalcorporation/zenfs pull request #86
Opened 2021-11-17 12:55 UTC by MaisenbacherD

For non-debug builds failing 'Acquire' and 'Release' calls where not
handled. Passing errors over to the calling function/application.

Reported-by: Hans Holmberg <hans.holmberg@wdc.com>
Suggested-by: Andreas Hindborg <andreas.hindborg@wdc.com>
Signed-off-by: Dennis Maisenbacher <dennis.maisenbacher@wdc.com>

2021-11-17 12:58 UTC, MaisenbacherD commented
This is a follow-up RP of https://github.com/metaspace/zenfs/pull/1

2021-11-19 14:03 UTC, yhr requested changes

2021-11-19 14:03 UTC, yhr commented on fs/zbd_zenfs.cc
> +inline IOStatus ZonedBlockDevice::CheckUnsetBusy(Zone *zone) {
And please move the check function to the zone class, then this code could be reused in MkFS as well.

2021-11-19 14:16 UTC, MaisenbacherD commented on fs/zbd_zenfs.h
> +  Status ResetUnusedIOZones();
Was no reason behind it. I will change it to IOStatus :)

2021-11-19 14:17 UTC, MaisenbacherD commented on fs/zbd_zenfs.cc
> +inline IOStatus ZonedBlockDevice::CheckUnsetBusy(Zone *zone) {
I will address both of your comments :)

2021-11-19 14:25 UTC, MaisenbacherD commented on fs/zbd_zenfs.h
> +  Status ResetUnusedIOZones();
Actually there was a reason: This function is just called in ZenFS::MkFS which also returns a Status.

2021-11-22 08:49 UTC, MaisenbacherD commented
Renamed and relocated ZonedBlockDevice::CheckUnsetBusy as suggested. 

Discussion for return type of ResetUnusedIOZones is open.

2021-11-22 15:16 UTC, yhr commented on fs/zbd_zenfs.h
> +  Status ResetUnusedIOZones();
Ah, I think we can change MkFs return IO status (as a separate patch)

2021-11-23 08:44 UTC, yhr commented
And please change the subject to "fs:..." (we use the subject prefix to tell the reader **what part** of the code is changed, not if it is a bugfix/feature etc)

2021-11-23 10:41 UTC, MaisenbacherD commented
Subject was changed :)

2021-11-23 12:45 UTC, MaisenbacherD commented
Unused variable was removed. Thanks for reporting @metaspace!

2021-11-23 14:41 UTC, MaisenbacherD commented
Rebased commit.

2021-11-23 19:28 UTC, yhr approved these changes
looks allright to me now!

2021-11-23 19:29 UTC, merged

2021-11-23 21:09 UTC, metaspace commented on fs/io_zenfs.cc
> +      if (!s.ok()) return s;
This is asking for ad stuff to happen :shrug: